#!/usr/bin/env python3
"""Generate docs/schema.sql from SQLAlchemy models or a SQLite database.

Two modes:

* **Model-based** (recommended; zero-config): derive the schema from your
  app's SQLAlchemy ``Base.metadata`` via ``create_all`` into a temp
  SQLite file.  Tests the code that's actually committed, works on fresh
  checkouts, no per-repo env wiring.

* **Live-DB**: read an existing SQLite database directly via the stdlib
  ``sqlite3`` module.  Useful for one-off auditing of a running system.

Usage
-----
::

    # Model-based (recommended)
    uv run python -m mcp_scripts.generate_schema_sql --models db.models:Base

    # Live-DB (explicit path)
    uv run python -m mcp_scripts.generate_schema_sql --database workspace.db

    # From environment (DATABASE_PATH or DATABASE_URL env vars)
    DATABASE_PATH=workspace.db uv run python -m mcp_scripts.generate_schema_sql

    # Full options
    uv run python -m mcp_scripts.generate_schema_sql \\
        --models  db.models:Base \\
        --output  docs/schema.sql \\
        --title   "My App database schema"

Environment variables (live-DB mode only)
-----------------------------------------
``DATABASE_PATH``
    Path to the SQLite ``.db`` file.  Takes precedence over ``DATABASE_URL``.
``DATABASE_URL``
    SQLAlchemy-style URL such as ``sqlite:///workspace.db``.  The path
    component is extracted automatically.

The command exits with status 0 on success, 1 on failure.
"""

from __future__ import annotations

import argparse
import importlib
import os
import re
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Database-path resolution
# ---------------------------------------------------------------------------

_DEFAULT_DB = "workspace.db"


def _resolve_db_path(explicit: str | None) -> Path:
    """Return the resolved database path from args or environment.

    Resolution order mirrors ``db/session.py`` in MCP server applications:

    1. ``--database`` CLI argument
    2. ``DATABASE_PATH`` environment variable
    3. Path extracted from ``DATABASE_URL`` (e.g. ``sqlite:///workspace.db``)
    4. Default: ``workspace.db`` (same default as the MCP server)
    """
    if explicit:
        return Path(explicit)

    db_path_env = os.getenv("DATABASE_PATH")
    if db_path_env:
        return Path(db_path_env)

    db_url_env = os.getenv("DATABASE_URL", "")
    if db_url_env:
        # Extract path from sqlite:///relative or sqlite:////absolute
        m = re.match(r"sqlite(?:\+\w+)?:///(.+)", db_url_env)
        if m:
            return Path(m.group(1))
        # DATABASE_URL is set but is not a recognised SQLite URL — warn so the
        # operator knows the fallback is being used rather than silently
        # targeting the wrong database.
        print(
            f"[schema-sql] WARNING: DATABASE_URL={db_url_env!r} is not a SQLite URL "
            f"(expected sqlite:///…). Falling back to '{_DEFAULT_DB}'.",
            file=sys.stderr,
        )

    return Path(_DEFAULT_DB)


# ---------------------------------------------------------------------------
# Schema extraction
# ---------------------------------------------------------------------------

_SECTION_SEP = "-" * 60

# Known shadow-table suffixes for FTS3/4 and FTS5 virtual tables.
# Using an explicit allowlist avoids false-positives from legitimate tables
# whose names happen to share a prefix with a virtual table.
_FTS_SHADOW_SUFFIXES: frozenset[str] = frozenset(
    {
        # FTS5
        "_data",
        "_idx",
        "_content",
        "_docsize",
        "_config",
        # FTS3/FTS4
        "_segments",
        "_segdir",
        "_stat",
    }
)


def _extract_schema(db_path: Path) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    """Return ``(tables, indexes)`` as lists of ``(name, ddl)`` tuples.

    Filters out:
    * SQLite internal objects (names starting with ``sqlite_``)
    * FTS / extension virtual tables (``CREATE VIRTUAL TABLE …``)
    * Shadow tables generated by virtual tables (``*_data``, ``*_idx``, etc.)
    * Implicit indexes created automatically for PRIMARY KEY / UNIQUE
      constraints (these appear in sqlite_master with ``sql IS NULL``)
    """
    with sqlite3.connect(str(db_path)) as conn:
        conn.row_factory = sqlite3.Row

        # Collect virtual table names first (excluded from the main query by the
        # sql NOT LIKE filter below, so we must query them separately).
        # Shadow tables (e.g. fts5_data, fts5_idx) share the virtual table's
        # name as a prefix and are filtered out in the loop below.
        virtual_rows = conn.execute(
            """
            SELECT name FROM sqlite_master
            WHERE type = 'table'
              AND sql LIKE 'CREATE VIRTUAL%'
            """
        ).fetchall()
        virtual_prefixes: set[str] = {row["name"] for row in virtual_rows}

        rows = conn.execute(
            """
            SELECT type, name, sql
            FROM sqlite_master
            WHERE type IN ('table', 'index')
              AND sql IS NOT NULL
              AND name NOT LIKE 'sqlite_%'
              AND sql NOT LIKE 'CREATE VIRTUAL%'
            ORDER BY type DESC, name ASC
            """
            # type DESC: 't' > 'i' so tables sort before indexes. Correct.
        ).fetchall()

    tables: list[tuple[str, str]] = []
    indexes: list[tuple[str, str]] = []

    for row in rows:
        name: str = row["name"]
        ddl: str = row["sql"].strip()
        kind: str = row["type"]

        # Skip shadow tables belonging to any virtual table.
        # Only exact known suffixes are matched; e.g. "search_index_backup" is
        # NOT skipped when the virtual table "search_index" exists because
        # "_backup" is not a recognised FTS shadow suffix.
        if virtual_prefixes and any(
            name == vp + suffix for vp in virtual_prefixes for suffix in _FTS_SHADOW_SUFFIXES
        ):
            continue

        if kind == "table":
            tables.append((name, ddl))
        else:
            indexes.append((name, ddl))

    return tables, indexes


# ---------------------------------------------------------------------------
# Output formatting
# ---------------------------------------------------------------------------


def _format_sql(
    tables: list[tuple[str, str]],
    indexes: list[tuple[str, str]],
    title: str,
) -> str:
    """Build the full schema SQL string."""
    lines: list[str] = [
        f"-- {title}",
        "-- DO NOT EDIT MANUALLY — regenerate with:",
        "--   uv run python -m mcp_scripts.generate_schema_sql",
        "",
        "PRAGMA foreign_keys = ON;",
        "PRAGMA journal_mode = WAL;",
    ]

    if tables:
        lines += ["", f"-- {_SECTION_SEP}", "-- TABLES", f"-- {_SECTION_SEP}"]
        for name, ddl in tables:
            lines += ["", f"-- {name}", ddl + ";"]

    if indexes:
        lines += ["", f"-- {_SECTION_SEP}", "-- INDEXES", f"-- {_SECTION_SEP}"]
        for name, ddl in indexes:
            lines += ["", f"-- {name}", ddl + ";"]

    lines.append("")  # trailing newline
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_schema(
    db_path: Path,
    title: str = "Database schema",
) -> str:
    """Return the schema SQL string for the database at *db_path*.

    Does **not** write to disk; call :func:`write_schema` for that.
    """
    tables, indexes = _extract_schema(db_path)
    return _format_sql(tables, indexes, title)


def write_schema(
    db_path: Path,
    output: Path,
    title: str = "Database schema",
) -> int:
    """Write schema SQL to *output*.  Returns number of tables written."""
    tables, indexes = _extract_schema(db_path)
    sql = _format_sql(tables, indexes, title)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(sql, encoding="utf-8")
    return len(tables)


# ---------------------------------------------------------------------------
# Model-based schema (zero-config)
# ---------------------------------------------------------------------------


def read_pythonpath_from_pyproject(cwd: Path | None = None) -> list[str]:
    """Return the ``pythonpath`` declared in ``pyproject.toml``.

    Looks for ``[tool.pytest.ini_options].pythonpath`` (the standard place
    Foundry-* / MCP-server repos already declare so pytest finds their
    code).  Returns an empty list if pyproject.toml is missing, malformed,
    or doesn't declare any pythonpath.

    This is the auto-detection path that makes ``--models db.models:Base``
    "just work" in repos whose code lives under ``mcp_servers/<name>/``
    rather than at the repo root — no additional CLI args needed.
    """
    cwd = cwd or Path.cwd()
    pyproject = cwd / "pyproject.toml"
    if not pyproject.exists():
        return []
    try:
        import tomllib  # stdlib, py3.11+
    except ImportError:
        return []
    try:
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return []
    raw = data.get("tool", {}).get("pytest", {}).get("ini_options", {}).get("pythonpath", [])
    if isinstance(raw, str):
        raw = [raw]
    if not isinstance(raw, list):
        return []
    return [str(p) for p in raw if isinstance(p, str)]


def prepend_models_paths(
    explicit_roots: list[str] | None = None,
    *,
    cwd: Path | None = None,
) -> list[str]:
    """Prepend the right directories to ``sys.path`` for model imports.

    Resolution order (highest precedence first):

    1. ``explicit_roots`` — values passed via ``--models-root`` on the
       command line.  If non-empty, the pyproject auto-detection is
       skipped (treated as a deliberate override).
    2. ``[tool.pytest.ini_options].pythonpath`` entries from
       ``pyproject.toml`` in *cwd*.  Skipped when ``explicit_roots`` is
       provided.
    3. The current working directory itself — always added last so it's
       the lowest-precedence fallback.

    Returns the absolute paths that were actually prepended, in
    insertion order, so callers can log them for debuggability.
    """
    cwd = cwd or Path.cwd()
    candidates: list[Path] = []
    if explicit_roots:
        candidates.extend(Path(r) for r in explicit_roots)
    else:
        candidates.extend(Path(r) for r in read_pythonpath_from_pyproject(cwd))
    candidates.append(cwd)

    added: list[str] = []
    # Insert at the front in reverse order so the highest-precedence path
    # ends up at index 0.
    for cand in reversed(candidates):
        resolved = str((cwd / cand).resolve())
        if resolved not in sys.path:
            sys.path.insert(0, resolved)
            added.insert(0, resolved)
    return added


def import_base(spec: str) -> Any:
    """Import ``module.path:Attr`` and return the attribute.

    *spec* uses Python entry-point convention: the part before the colon is
    a dotted module path, the part after is an attribute name on that
    module (typically your SQLAlchemy declarative ``Base``).

    Raises ``SystemExit(2)`` with a human-readable error on failure so the
    error reaches pre-commit / CI output cleanly.
    """
    if ":" not in spec:
        print(
            f"[schema-sql] ERROR: --models must be in the form 'module.path:Attr', got: {spec!r}",
            file=sys.stderr,
        )
        sys.exit(2)
    module_path, _, attr_name = spec.partition(":")
    if not module_path or not attr_name:
        print(
            f"[schema-sql] ERROR: --models must be in the form 'module.path:Attr', got: {spec!r}",
            file=sys.stderr,
        )
        sys.exit(2)
    try:
        module = importlib.import_module(module_path)
    except ImportError as exc:
        print(
            f"[schema-sql] ERROR: failed to import {module_path!r}: {exc}\n"
            "Make sure you are running via 'uv run' (or another way that puts\n"
            "your project on sys.path).",
            file=sys.stderr,
        )
        sys.exit(2)
    if not hasattr(module, attr_name):
        print(
            f"[schema-sql] ERROR: module {module_path!r} has no attribute {attr_name!r}",
            file=sys.stderr,
        )
        sys.exit(2)
    return getattr(module, attr_name)


def generate_schema_from_models(
    base: Any,
    title: str = "Database schema",
) -> str:
    """Return the schema SQL implied by *base*'s SQLAlchemy metadata.

    Materialises ``base.metadata.create_all`` into a temporary SQLite file
    (deleted before return) and runs the same :func:`generate_schema`
    extractor over it.  This means the model-derived output passes through
    identical formatting + filtering logic as the live-DB path — so the
    two modes produce byte-identical schema.sql files for the same
    declared shape.
    """
    # Lazy import: keeps the script importable for argv-parse tests in
    # environments where SQLAlchemy isn't installed.
    from sqlalchemy import create_engine

    tmp = tempfile.NamedTemporaryFile(suffix=".db", delete=False)
    tmp.close()
    tmp_path = Path(tmp.name)
    try:
        engine = create_engine(f"sqlite:///{tmp_path}")
        try:
            base.metadata.create_all(engine)
        finally:
            engine.dispose()
        return generate_schema(tmp_path, title=title)
    finally:
        try:
            tmp_path.unlink()
        except OSError:
            pass


def write_schema_from_models(
    base: Any,
    output: Path,
    title: str = "Database schema",
) -> int:
    """Write the model-derived schema SQL to *output*.

    Returns the number of tables written.
    """
    sql = generate_schema_from_models(base, title=title)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(sql, encoding="utf-8")
    # Count tables by re-parsing — cheaper than another create_all round-trip.
    return sum(1 for line in sql.splitlines() if line.startswith("CREATE TABLE"))


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate docs/schema.sql from SQLAlchemy models or a SQLite database.\n\n"
            "Recommended (zero-config):\n"
            "  --models db.models:Base\n\n"
            "Alternative (live database):\n"
            "  --database workspace.db   (or DATABASE_PATH / DATABASE_URL env)"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    source = parser.add_mutually_exclusive_group()
    source.add_argument(
        "--models",
        metavar="MODULE:ATTR",
        default=None,
        help=(
            "Import path of the SQLAlchemy declarative Base, in the form "
            "'module.path:Attr' (e.g. 'db.models:Base').  Derives the schema "
            "from Base.metadata via create_all into a temp SQLite file."
        ),
    )
    source.add_argument(
        "--database",
        metavar="PATH",
        default=None,
        help="Path to the live SQLite .db file (overrides DATABASE_PATH / DATABASE_URL).",
    )
    parser.add_argument(
        "--models-root",
        metavar="DIR",
        action="append",
        default=None,
        help=(
            "Directory to prepend to sys.path before resolving --models. "
            "Repeat for multiple roots.  When omitted, "
            "[tool.pytest.ini_options].pythonpath from pyproject.toml is "
            "used; this lets repos that put server code under "
            "mcp_servers/<name>/ resolve 'db.models:Base' without any "
            "extra wiring."
        ),
    )
    parser.add_argument(
        "--output",
        metavar="PATH",
        default="docs/schema.sql",
        help="Output file path (default: docs/schema.sql).",
    )
    parser.add_argument(
        "--title",
        metavar="TEXT",
        default="Database schema",
        help="Title comment written at the top of the file.",
    )
    args = parser.parse_args(argv)

    output = Path(args.output)

    if args.models is not None:
        prepend_models_paths(args.models_root)

        base = import_base(args.models)
        n_tables = write_schema_from_models(base, output, title=args.title)
        print(f"Schema written to {output}  ({n_tables} tables, from {args.models})")
        return 0

    db_path = _resolve_db_path(args.database)

    if not db_path.exists():
        sys.exit(
            f"Database file not found: {db_path}\n"
            "Create or populate the database first (e.g. mise run start or mise run populate),\n"
            "then re-run this command."
        )

    n_tables = write_schema(db_path, output, title=args.title)
    print(f"Schema written to {output}  ({n_tables} tables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
