#!/usr/bin/env python
"""Generate wrapper scripts for mercor-mcp-shared modules.

This script creates thin wrapper scripts in the local `scripts/` directory
that delegate to the actual implementations in mercor-mcp-shared.

The script is idempotent - running it multiple times will only update
wrappers that are missing or out of date.

To prevent a local script from being replaced with a wrapper, add this
comment at the top of the file:

    # mercor-mcp-shared: no-wrapper
"""

import importlib.util
import sys
from pathlib import Path

# Files that shouldn't have wrappers
SKIP_FILES = {
    "__init__.py",
    "__pycache__",
}

# Marker comment to prevent wrapper generation for a local script
# Add this at the top of a script to keep a local implementation
SKIP_MARKER = "# mercor-mcp-shared: no-wrapper"

# Extensions that shouldn't have wrappers (shell scripts, etc.)
SKIP_EXTENSIONS = {
    ".sh",
    ".bash",
    ".md",
    ".txt",
    ".json",
    ".yaml",
    ".yml",
}

# Subdirectories to skip
SKIP_DIRS = {
    "__pycache__",
    "prompts",
}

WRAPPER_TEMPLATE = '''#!/usr/bin/env python
"""{description}

Implementation: mercor-mcp-shared/mcp_scripts/{module_name}.py
"""

import sys

from mcp_scripts import {module_name}

sys.modules[__name__] = {module_name}

if __name__ == "__main__":
    sys.exit({module_name}.main())
'''


def get_module_description(module_path: Path) -> str:
    """Extract the module's docstring by importing it."""
    try:
        spec = importlib.util.spec_from_file_location(module_path.stem, module_path)
        if spec and spec.loader:
            module = importlib.util.module_from_spec(spec)
            # Execute module to populate __doc__ (side effects caught by try/except)
            spec.loader.exec_module(module)
            if module.__doc__:
                # Return first line only
                return module.__doc__.strip().split("\n")[0]
    except Exception:
        pass
    return f"Wrapper for {module_path.stem}."


def is_valid_python_identifier(name: str) -> bool:
    """Check if a name is a valid Python identifier."""
    return name.isidentifier()


def should_create_wrapper(module_path: Path) -> bool:
    """Check if a file should have a wrapper created."""
    # Skip directories
    if module_path.is_dir():
        return False

    # Skip by name
    if module_path.name in SKIP_FILES:
        return False

    # Skip by extension
    if module_path.suffix in SKIP_EXTENSIONS:
        return False

    # Only Python files
    if module_path.suffix != ".py":
        return False

    # Module name must be valid Python identifier (no hyphens, can't start with digit)
    if not is_valid_python_identifier(module_path.stem):
        return False

    # Check if module has a main() function
    try:
        content = module_path.read_text()
        if "def main(" not in content:
            return False
    except Exception:
        return False

    return True


def looks_like_generated_wrapper(content: str) -> bool:
    """Check if content looks like a generated wrapper (even if outdated).

    This distinguishes between:
    - A file generated by this script (even if template changed)
    - A local implementation that just mentions mercor-mcp-shared in a comment

    Requires BOTH markers to be present to avoid overwriting legitimate local
    scripts that happen to use one of the patterns (e.g., sys.modules assignment).
    """
    # Check for structural markers unique to generated wrappers
    # Both markers must be present to identify as a generated wrapper
    structural_markers = [
        "Implementation: mercor-mcp-shared",  # From docstring template
        "sys.modules[__name__] =",  # Key wrapper pattern
    ]
    return all(marker in content for marker in structural_markers)


def is_valid_wrapper(wrapper_path: Path, module_name: str) -> bool:
    """Check if an existing file is a valid wrapper for the module."""
    if not wrapper_path.exists():
        return False

    try:
        content = wrapper_path.read_text()

        # Check for wrapper pattern markers
        markers = [
            f"from mcp_scripts import {module_name}",
            f"sys.modules[__name__] = {module_name}",
            "mercor-mcp-shared",
        ]

        return all(marker in content for marker in markers)
    except Exception:
        return False


def generate_wrapper(module_name: str, description: str) -> str:
    """Generate wrapper script content."""
    # Escape special characters that would break the template
    safe_description = description.replace("{", "{{").replace("}", "}}")
    # Escape triple quotes that would break the wrapper's docstring
    safe_description = safe_description.replace('"""', '\\"\\"\\"')
    return WRAPPER_TEMPLATE.format(module_name=module_name, description=safe_description)


def find_mcp_scripts_modules(shared_root: Path) -> list[Path]:
    """Find all Python modules in mcp_scripts that should have wrappers."""
    mcp_scripts = shared_root / "mcp_scripts"
    if not mcp_scripts.exists():
        return []

    modules = []
    for path in mcp_scripts.iterdir():
        if path.is_dir() and path.name in SKIP_DIRS:
            continue
        if should_create_wrapper(path):
            modules.append(path)

    return sorted(modules)


def find_shared_repo(start_path: Path) -> Path | None:
    """Try to find the mercor-mcp-shared repo."""
    candidates = [
        start_path.parent / "mercor-mcp-shared",
        start_path / ".." / "mercor-mcp-shared",
        Path.home() / "mercor-mcp-shared",
        Path("/workspaces/mercor-mcp-shared"),
    ]

    for candidate in candidates:
        resolved = candidate.resolve()
        if (resolved / "mcp_scripts").exists():
            return resolved

    return None


def main(
    repo_root: Path | None = None, shared_root: Path | None = None, dry_run: bool = False
) -> int:
    """Main entry point.

    Args:
        repo_root: Root of the repository to update. Defaults to current directory.
        shared_root: Root of mercor-mcp-shared. Auto-detected if not provided.
        dry_run: If True, don't write changes.

    Returns:
        Exit code (0 for success).
    """
    if repo_root is None:
        repo_root = Path.cwd()

    if shared_root is None:
        shared_root = find_shared_repo(repo_root)
        if shared_root is None:
            print("Error: Could not find mercor-mcp-shared repository.")
            print("Please specify with --shared-root or ensure it's in a sibling directory.")
            return 2

    scripts_dir = repo_root / "scripts"
    scripts_dir.mkdir(exist_ok=True)

    print(f"Local repository: {repo_root}")
    print(f"Shared repository: {shared_root}")
    print(f"Scripts directory: {scripts_dir}")
    print(f"Dry run: {dry_run}")
    print()

    modules = find_mcp_scripts_modules(shared_root)
    print(f"Found {len(modules)} modules in mcp_scripts/")

    created = []
    updated = []
    unchanged = []
    skipped = []

    for module_path in modules:
        module_name = module_path.stem
        wrapper_path = scripts_dir / f"{module_name}.py"

        # Check if valid wrapper already exists
        if is_valid_wrapper(wrapper_path, module_name):
            unchanged.append(module_name)
            continue

        # Check if there's a non-wrapper file we shouldn't overwrite
        if wrapper_path.exists():
            try:
                content = wrapper_path.read_text()
            except OSError:
                # Can't read file, skip it
                skipped.append(module_name)
                continue
            if SKIP_MARKER in content:
                # Explicitly marked to keep local implementation
                skipped.append(module_name)
                continue
            if not looks_like_generated_wrapper(content):
                # This is a local implementation (may mention mercor-mcp-shared
                # in comments but lacks wrapper structure)
                skipped.append(module_name)
                continue
            # It's an outdated wrapper (has wrapper structure), update it
            action = "updated"
            updated.append(module_name)
        else:
            action = "created"
            created.append(module_name)

        # Generate wrapper
        description = get_module_description(module_path)
        wrapper_content = generate_wrapper(module_name, description)

        if not dry_run:
            wrapper_path.write_text(wrapper_content)
            # Make executable
            wrapper_path.chmod(0o755)

        print(f"  {action}: {wrapper_path.name}")

    # Report
    print()
    print("Summary:")
    print(f"  Created: {len(created)}")
    print(f"  Updated: {len(updated)}")
    print(f"  Unchanged: {len(unchanged)}")
    print(f"  Skipped (local implementation): {len(skipped)}")

    if skipped:
        print()
        print("Skipped files (have local implementations):")
        for name in skipped:
            print(f"  - {name}.py")

    if dry_run and (created or updated):
        print()
        print("(Dry run - no files were modified)")

    return 0


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo", type=Path, default=Path.cwd(), help="Repository root (default: current directory)"
    )
    parser.add_argument(
        "--shared-root",
        type=Path,
        default=None,
        help="Path to mercor-mcp-shared (auto-detected if not provided)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Don't write changes, just report what would be done"
    )
    args = parser.parse_args()

    sys.exit(main(args.repo, args.shared_root, args.dry_run))
